name: Terraform Plan

on:
  pull_request:
    branches: [ master ]
    paths: [ 'infra/azappsrv_terraform/**' ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: "e6b85452-b679-471d-97b4-a82acc7275aa"
      ARM_TENANT_ID: "3bfe060a-b6cc-46cf-898b-b5c2543620ff"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./infra/azappsrv_terraform
        run: terraform init

      - name: Terraform Format
        working-directory: ./infra/azappsrv_terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./infra/azappsrv_terraform
        run: terraform plan